northwind:
  outputs:
    dev:
      type: snowflake
      threads: 1
      account: RCB74488
      user: dbt
      password: ddbt
      role: DBT_RW
      warehouse: ETL
      database: NORTHWIND
      schema: RAW 
  target: dev